// imports
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
// images
import Image from "next/image";
import p2 from "../public/p2.png";
import design from "../public/design.png";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
// hooks
import { useState } from "react";

// applicaiton
export default function Home() {
  // functions
  const [darkmode, setdarkmode] = useState(false);
  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>hello there</title>
        <meta name="description" content="Generated by create next app" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-poppins bg-white px-10 md:px -20 lg:px-40 dark:bg-black">
        <section className="min-h-screen">
          <nav className="py-10 mb12 flex justify-between">
            <h1 className=" text-xl dark:text-white">Developed by Samin</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li>
              <li>
                <a
                  href="#"
                  className=" bg-purple-600 text-white px-4 py-2 boder-none rounded-md "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div className="text-center p-10 ">
            <h2 className=" text-5xl font-bold text-purple-700 md:text-6xl lg:text-7xl lg:mb-4">
              Samin Chandeepa
            </h2>
            <h3 className="text-2xl py-4 md:text-3xl dark:text-white">
              Mobile Apps and website developer
            </h3>
            <p className=" text-sm py-2 text-gray-400 leading-6 md:text-md  max-w-xl mx-auto">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil fugiat ea perferendis qui nulla facere
              consequaturipsum dolor sit amet consectetur adipisicing elit.
              Itaque distinctio nihil fugiat ea perferendis qui nulla facere
              consequatur
            </p>
          </div>
          {/* social media */}
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiOutlineTwitter />
          </div>
          {/* profile image */}
          <div
            className=" m-auto
           relative bg-gradient-to-b from-purple-200 w-80 p-5
            h-80 mt-20   rounded-full o"
          >
            <Image src={p2} alt="profile" layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* section 2 */}

        <section>
          <div>
            <h3 className=" text-3xl py-10 font-bold opacity-60 dark:text-white dark:opacity-100">
              Services I offer
            </h3>
            <p className=" text-sm py-2 text-gray-400 leading-6">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil fugiat ea perferendis qui nulla facere
              consequatur dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil perferendis qui nulla facere consequatur dolor
              sit amet consectetur adipisicing elit. Itaque distinctio nihil
            </p>
          </div>
          <div className="md:flex lg:flex gap-10 mx-auto">
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
              <Image
                src={design}
                width={100}
                height={100}
                alt="design"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white ">
                Graphic Desinging
              </h3>
              <p className=" text-sm py-2 text-gray-400 leading-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
                distinctio nihil fugiat ea perferendis qui nulla facere
                consequatur
              </p>
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Design tools I use
              </h4>
              <p className=" text-gray-400 text-sm">Photoshop</p>
              <p className=" text-gray-400 text-sm">Figma</p>
              <p className=" text-gray-400 text-sm">Illustrator</p>
              <p className=" text-gray-400 text-sm">After effects</p>
            </div>
            {/*  */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <Image
                src={code}
                width={100}
                height={100}
                alt="design"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white">
                Application development
              </h3>
              <p className=" text-sm py-2 text-gray-400 leading-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
                distinctio nihil fugiat ea perferendis qui nulla facere
                consequatur
              </p>
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Design tools I use
              </h4>
              <p className=" text-gray-400 text-sm">Photoshop</p>
              <p className=" text-gray-400 text-sm">Figma</p>
              <p className=" text-gray-400 text-sm">Illustrator</p>
              <p className=" text-gray-400 text-sm">After effects</p>
            </div>
            {/*  */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <Image
                src={design}
                width={100}
                height={100}
                alt="design"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white">consulting</h3>
              <p className=" text-sm py-2 text-gray-400 leading-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
                distinctio nihil fugiat ea perferendis qui nulla facere
                consequatur
              </p>
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Design tools I use
              </h4>
              <p className=" text-gray-400 text-sm">Photoshop</p>
              <p className=" text-gray-400 text-sm">Figma</p>
              <p className=" text-gray-400 text-sm">Illustrator</p>
              <p className=" text-gray-400 text-sm">After effects</p>
            </div>
          </div>
        </section>

        {/* last section */}
        <section>
          <div>
            <h3 className=" text-3xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100">
              Portofolio
            </h3>
            <p className=" text-sm py-2 text-gray-400 leading-6">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil fugiat ea perferendis qui nulla facere
              consequatur dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil perferendis qui nulla facere consequatur dolor
              sit amet consectetur adipisicing elit. Itaque distinctio nihil
            </p>
          </div>
          {/* images */}
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web images"
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web images"
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web images"
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web images"
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web images"
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web images"
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
